# Generated by Django 5.1.7 on 2025-03-15 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0003_alter_department_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="face_encoding",
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
