# Generated by Django 5.1.7 on 2025-03-18 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0004_profile_face_encoding"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="face_encoding",
        ),
    ]
