# Generated by Django 5.1.7 on 2025-03-19 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0005_remove_profile_face_encoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="face_encoding",
            field=models.TextField(blank=True, null=True),
        ),
    ]
