# Generated by Django 5.1.7 on 2025-03-24 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0006_profile_face_encoding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Active", "Active"), ("Inactive", "Inactive")],
                max_length=20,
                null=True,
            ),
        ),
    ]
