# Generated by Django 5.1.7 on 2025-03-24 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("App", "0007_alter_employee_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Admin", "Admin"),
                    ("Staff", "Staff"),
                    ("Employee", "Employee"),
                ],
                max_length=50,
                null=True,
            ),
        ),
    ]
